# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Statistics-Descriptive-Weighted
version:      0.1
version_from: Weighted.pm
installdirs:  site
requires:
    Statistics::Descriptive:       2.6

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
